namespace StockAnalyzer.DataProviders.Types.UsGaap
{
    /// <summary>
    /// Autogenerated from https://data.sec.gov/api/xbrl/companyconcept/CIK0000200406/us-gaap/LongTermDebt.json
    /// </summary>
    public class LongTermDebt
    {
        public int cik { get; set; }
        public string taxonomy { get; set; }
        public string tag { get; set; }
        public string label { get; set; }
        public string description { get; set; }
        public string entityName { get; set; }
        public Units units { get; set; }
    }
}

