using System.Collections.Generic;

namespace StockAnalyzer.DataProviders.Types
{
    /// <summary>
    /// Autogenerated from https://www.sec.gov/files/company_tickers_exchange.json
    /// </summary>
    public class CompanyTickersExchange
    {
        public List<string> fields { get; set; }
        public List<List<object>> data { get; set; }
    }
}
