@startuml reqContractDetails

start
:var signal = new EReaderMonitorSignal()
var eWrapperImpl = new EWrapperImpl(signal);

:eWrapperImpl.ClientSocket.eConnect(host, port, cClientId);
note left
eWrapperImpl 
alias IbClient
endnote
:var reader = new EReader(ibClient.ClientSocket, signal);

fork
    :main thread;
    :eWrapperImpl.ClientSocket.reqContractDetails(reqId, contract);
fork again
  :eReader thread;
    while (eWrapperImpl.ClientSocket.IsConnected())
        :signal.waitForSignal();
        : reader.processMsgs();
    endwhile
end fork
stop

@enduml
